### ISSUE TITLE
redefined nodes in fixNoFishNodes()

### ISSUE THREAD

**Issue by mackerman44** [KevinSee/DABOM#34]
When running `jags.model()` to initiate a DABOM model run, I'm getting an error "Attempt to redefine node" which, at least for SY2015 Chinook, occurs for phi_VC2[1] (lines 413-414 in [lgr_dabom_jags_Chinook_SY2021.txt](https://github.com/KevinSee/DABOM/files/12353127/lgr_dabom_jags_Chinook_SY2021.txt)) and for phi_SC2[1] (lines 374-375) when using the JAGS model file from `fixNoFishNodes()`.

It seems I can easily resolve this simply by changing the [1] to a [2] on the second line in both cases. The odd thing is that this isn't reflected in 
[lgr_dabom_jags.txt](https://github.com/KevinSee/DABOM/files/12353140/lgr_dabom_jags.txt), which is created using `writeDABOM()`.

This error is occurs in the 
[05_dabom.txt](https://github.com/KevinSee/DABOM/files/12353200/05_dabom.txt) script located in the SRB_OncorPopStatus repo [here](https://github.com/NPTfisheries/SRB_OncorPopStatus/blob/main/scripts/05_dabom.R).

**Comment by KevinSee** [comment]
Found a bug in `fixNoFishNodes` that was determining origin incorrectly when a site has a numeral in its name. The bug has been fixed in the `npt_dev_ks` branch.
