### ISSUE TITLE
Don't drop Fall Chinook tags

### ISSUE THREAD

**Issue by KevinSee** [KevinSee/DABOM#8]
Because fall Chinook are included in STADEM estimates, any valid tags from fall Chinook should NOT be excluded before running DABOM. Presumably they all end up in the main black box, but that should be checked.

**Comment by ryankinzer** [comment]
This was already fixed by one of us commenting out a code chunk in PITcleanR::filterLGRtrapDB() where we only used records with '5' in the SRR field if species == Chinook.

**Comment by KevinSee** [comment]
Good catch Ryan.
